[project]
name = "dbs-eeg-sync"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "mne>=1.9.0",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pyxdf",
    "plotly"
]

[tool.hatch.build.targets.wheel]
packages = ["source"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
dbs_eeg_sync = "dbs_eeg_sync.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["dbs_eeg_sync*", "source*"]